package email

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// Request is everything needed to compose one deletion request.
type Request struct {
	BrokerName  string
	BrokerEmail string
	SubjectName string
	SubjectMail string
	SubjectState string
}

// The request is rendered from a fixed template rather than generated by a
// model.
//
// CLAUDE.md originally planned to draft these with Sonnet "so they sound
// legitimate and professional". That is the wrong tool for this job. This is a
// statutory request whose force comes from citing the right law and stating
// the right facts, and it is sent in the account owner's name - so it must be
// identical every time, auditable after the fact, and incapable of inventing a
// claim he did not make. A template is all three. A model here would buy
// nothing but variance and the chance of a fabricated assertion going out
// under a real person's signature.
const ccpaBody = `To the Privacy Officer at {{.BrokerName}},

{{.Preamble}}

Identifying information for the purpose of locating my records:

  Name:  {{.SubjectName}}
  Email: {{.SubjectMail}}
  State: {{.SubjectState}}

This request covers all personal information in your possession, including data
obtained from third-party sources and any inferences drawn from it.

I additionally request, to the extent applicable:

  1. That you do not sell or share my personal information (opt-out of sale).
  2. Confirmation in writing once deletion is complete.
  3. The categories of sources from which my information was collected.

If you require additional information to verify my identity, tell me
specifically what is needed and I will provide it - but please do not request
more personal information than is necessary to verify this request, and do not
use anything provided for verification for any other purpose.

I look forward to your confirmation.

Regards,
{{.SubjectName}}
{{.SubjectMail}}
`

// statutePreambles maps a state to the opening paragraph that is true for a
// resident of that state.
//
// This exists because the first version of this letter opened with "I am a
// California-resident-equivalent consumer exercising my statutory right to
// deletion" and sent it on behalf of an Ohio resident. There is no such thing
// as California-resident-equivalent. CCPA rights attach to California
// residents, and asserting residency you do not have, in a request whose
// entire force comes from being a verifiable statutory claim, is a
// misstatement made in the sender's name to a company that keeps records.
//
// Only states whose comprehensive consumer privacy statute is named here get a
// citation. Everyone else gets the neutral preamble, which is true everywhere:
// it asks for the right under any law that does apply, and under the broker's
// own published policy where none does. That is weaker rhetoric and an honest
// claim, which is the correct trade for a letter going out over a real
// signature.
//
// This list is not legal advice and is certainly incomplete - state privacy
// law has been moving fast. Adding a state means checking that its statute is
// actually in effect.
var statutePreambles = map[string]string{
	"CA": `I am a California resident exercising my right to deletion under the
California Consumer Privacy Act, as amended by the California Privacy Rights
Act (Cal. Civ. Code section 1798.105). I request that you delete all personal
information you have collected about me, and direct any service providers and
contractors to do the same. Please treat this as a verifiable consumer
request.`,
	"VA": `I am a Virginia resident exercising my right to deletion under the
Virginia Consumer Data Protection Act. I request that you delete all personal
data you have collected about me, and direct any processors to do the same.`,
	"CO": `I am a Colorado resident exercising my right to deletion under the
Colorado Privacy Act. I request that you delete all personal data you have
collected about me, and direct any processors to do the same.`,
	"CT": `I am a Connecticut resident exercising my right to deletion under the
Connecticut Data Privacy Act. I request that you delete all personal data you
have collected about me, and direct any processors to do the same.`,
	"UT": `I am a Utah resident exercising my right to deletion under the Utah
Consumer Privacy Act. I request that you delete all personal data you have
collected about me, and direct any processors to do the same.`,
	"TX": `I am a Texas resident exercising my right to deletion under the Texas
Data Privacy and Security Act. I request that you delete all personal data you
have collected about me, and direct any processors to do the same.`,
	"OR": `I am an Oregon resident exercising my right to deletion under the
Oregon Consumer Privacy Act. I request that you delete all personal data you
have collected about me, and direct any processors to do the same.`,
}

const neutralPreamble = `I am writing to request the deletion of all personal information you hold
about me, and to ask that you direct any service providers or processors to do
the same.

To the extent that any state consumer privacy law applies to me or to your
processing of my information, I am exercising my right to deletion and my right
to opt out of the sale or sharing of my personal information under that law.
Where no such law applies, I ask that you honour this request under your own
published privacy policy and your stated opt-out process.`

// Preamble returns the opening paragraph appropriate to the subject's state.
func (r Request) Preamble() string {
	if p, ok := statutePreambles[strings.ToUpper(strings.TrimSpace(r.SubjectState))]; ok {
		return p
	}
	return neutralPreamble
}

var ccpaTmpl = template.Must(template.New("ccpa").Parse(ccpaBody))

// Subject line for the request.
func (r Request) Subject() string {
	return fmt.Sprintf("Consumer Request to Delete Personal Information - %s", r.SubjectName)
}

// Body renders the request text.
func (r Request) Body() (string, error) {
	var buf bytes.Buffer
	if err := ccpaTmpl.Execute(&buf, r); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// Validate refuses to compose a request that is missing anything a broker
// needs in order to act on it.
//
// An incomplete request is worse than no request: it starts the clock, gets
// rejected as unverifiable, and leaves a record suggesting the matter was
// handled. Better to fail loudly here than to send something that cannot
// succeed.
func (r Request) Validate() error {
	var missing []string
	if strings.TrimSpace(r.BrokerEmail) == "" {
		missing = append(missing, "broker email (run `discover` first)")
	}
	if strings.TrimSpace(r.SubjectName) == "" {
		missing = append(missing, "SUBJECT_NAME")
	}
	if strings.TrimSpace(r.SubjectMail) == "" {
		missing = append(missing, "SUBJECT_EMAIL")
	}
	if strings.TrimSpace(r.SubjectState) == "" {
		missing = append(missing, "SUBJECT_STATE")
	}
	if len(missing) > 0 {
		return fmt.Errorf("cannot compose a request, missing: %s", strings.Join(missing, ", "))
	}
	return nil
}

// RFC822 builds the raw message. Gmail wants RFC 2822 text, base64url encoded
// by the caller.
func (r Request) RFC822() (string, error) {
	body, err := r.Body()
	if err != nil {
		return "", err
	}
	var b strings.Builder
	fmt.Fprintf(&b, "To: %s\r\n", r.BrokerEmail)
	fmt.Fprintf(&b, "Subject: %s\r\n", r.Subject())
	fmt.Fprintf(&b, "MIME-Version: 1.0\r\n")
	fmt.Fprintf(&b, "Content-Type: text/plain; charset=UTF-8\r\n")
	fmt.Fprintf(&b, "\r\n")
	b.WriteString(strings.ReplaceAll(body, "\n", "\r\n"))
	return b.String(), nil
}
